const rigsData = [
  {
    id: 1,
    status: "available",
    name: "NRS Expedition-136 - fully rigged",
    brand: "NRS",
    type: "Multi-day",
    cost: 195,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "The 13 ft 6in NRS E-136 plays like a 13' boat and works like a 14' boat. Its aggressive rocker and wide stance make it fun but dependable in the rapids. Great for fishing, overnights and just seeking thrills.",
    photoId: "rigs-NRS-4.png",
  },
  {
    id: 2,
    status: "available",
    name: "RMR PK-134 - partially rigged",
    brand: "RMR",
    type: "Multi-day",
    cost: 175,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "Introducing RMR's series of lightweight, plug n' play frame packages. The Rocky Mountain Raft 13' 3-Bay Raft Frame Package for the SB-130 comes with EVERYTHING you need to hit the river in style.",
    photoId: "rigs-RMR-6.png",
  },
  {
    id: 3,
    status: "available",
    name: "Hyside Outfitter 14.0 - partially rigged",
    brand: "Hyside",
    type: "Overnight",
    cost: 190,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "For the longest time a 14 ft has always been the all around boat. Great for high water, yet floats you over the rocks when the water drops. Lots of leg room to paddle and ample room for a rowing rig.",
    photoId: "rigs-Hyside-10.png",
  },
  {
    id: 4,
    status: "available",
    name: "10.5 RMR Storm 3-Bay Frame - fully rigged",
    brand: "RMR",
    type: "Fishing",
    cost: 125,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "Introducing RMR's series of lightweight, plug n' play frame packages. The RMR Storm 3-Bay Frame with Poly Deck Package comes with EVERYTHING you need to hit the river in style. Choose your color of our Storm - and leave the rest to us. Our RMR Frame is hand-crafted in Fayette County, WV. The RMR 3-Bay Frame with Poly Deck uses 1-1/4 ft Schedule 40 6063 T6 anodized aluminum with Hollaender Speed Rail Fittings and includes a kick bar, custom oar towers, high-density (HDPE) poly deck, and (4) 1' cam straps. Add in Sawyer components and you have everything you need for the ultimate rowing machine!",
    photoId: "rigs-RMR-7.png",
  },
  {
    id: 5,
    status: "available",
    name: "Maravia 14X24 Cataraft - fully rigged",
    brand: "Maravia",
    type: "Multi-day",
    cost: 215,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "Smooth curved bow and stern profiles on this highly maneuverable cataraft cut the water more like a hard hull and gives better handling characteristics.",
    photoId: "rigs-Maravia-6.png",
  },
  {
    id: 6,
    status: "available",
    name: "Hyside Pro 16.0 - fully rigged",
    brand: "Hyside",
    type: "Multi-day",
    cost: 195,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "Designed to carry 8 loads with ease, the PRO 16.0 delivers and feels like youre driving a 14. Load it down with gear, this boat crushes big water while still staying nimble.",
    photoId: "rigs-Hyside-8.png",
  },
  {
    id: 7,
    status: "available",
    name: "14'6 STREAMTECH STEELHEAD - fully rigged",
    brand: "Maravia",
    type: "Fishing",
    cost: 165,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "The Steelhead offers the same bow and stern rockered hull engineering with all Streamtech Boats that brings outstanding rowing performance to inflatables. The hull glides out on the waters film, spins effortlessly and just plain rows really good. It carries heavy loads, drafts shallow and offers a three cargo bay frame design allowing a broad array of configuration possibilities.",
    photoId: "rigs-Maravia-4.png",
  },
  {
    id: 8,
    status: "available",
    name: "13' WIDER SPIDER - partially rigged",
    brand: "Maravia",
    type: "Multi-day",
    cost: 180,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "This baby was born extra wide! We made room for larger boxes and a bigger cooler without compromising the exceptional performance of the traditional Spider. In fact, the added girth provides additional room for comfortable passengers, extra supplies, and increased stability.",
    photoId: "rigs-Maravia-3.png",
  },
  {
    id: 9,
    status: "available",
    name: "14 RMR Frame Package - partially rigged",
    brand: "RMR",
    type: "Overnight",
    cost: 130,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "Introducing RMR's series of lightweight, plug n' play frame packages. The Rocky Mountain Raft 4-Bay 14' Raft Frame Package comes with EVERYTHING you need to hit the river in style. Choose the color of your SB-140 (I-Beam floor) - and leave the rest to us.  RMR Frames are made in Fayette County, WV by our experienced frame designer and craftsman.  The RMR 4-Bay Frame is hand-crafted from 1-1/2 Sch 40 6063 T6 Anodized Aluminum with Hollaender Speed Rail Fittings and includes a kick bar and custom oar towers.  We've added Sawyer components, a poly deck, drop bags, and cam straps...just add water and you're ready to fish the eddies or overnight in style",
    photoId: "rigs-RMR-8.png",
  },
  {
    id: 10,
    status: "available",
    name: "MAX 12.0 - fully rigged",
    brand: "Hyside",
    type: "Overnight",
    cost: 170,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "MAX VERSATILITY: Rounding out the Mini line comes the NEW MAX 12.0. RAFTING IS DYNAMIC. Thats why it never gets old. From exploring new rivers and experiencing fluctuating flows, to switching from a paddle crew to a fishing set up: the options are limitless. With so many possibilities, its hard to get a boat that does it all. Thats where the Max 12.0 comes in. Riding on the same versatile design as the Mini-Me and Mini-Max, the Max 12.0 comes stock with three removable thwarts, a 74” straight section and 19” tubes. This raft can handle a boatload.",
    photoId: "rigs-Hyside-9.png",
  },
  {
    id: 11,
    status: "available",
    name: "Outfitter 12.0 - partially rigged",
    brand: "Hyside",
    type: "Multi-day",
    cost: 210,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "This “big tube, little boat” design offers the perfect blend of big water stability and capacity. And its not uncommon to see it run with a third thwart.",
    photoId: "rigs-Hyside-7.png",
  },
  {
    id: 12,
    status: "available",
    name: "14 RMR Frame Package - fully rigged",
    brand: "RMR",
    type: "Multi-day",
    cost: 185,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "Introducing RMR's series of lightweight, plug n' play frame packages. The Rocky Mountain Raft 4-bay 14' Frame Package comes with EVERYTHING you need to hit the river in style. Choose your color of the SBDS-140 (drop-stitch floor) - and leave the rest to us. RMR Frames are made in Fayette County, WV by our experienced frame designer and craftsman.  The RMR 4-Bay Frame is hand-crafted from  1-1/2 Sch 40 6063 T6 Anodized Aluminum with Hollaender Speed Rail Fittings and includes a kick bar and custom oar towers.",
    photoId: "rigs-RMR-6.png",
  },
  {
    id: 13,
    status: "available",
    name: "13' TORRENT - fully rigged",
    brand: "Maravia",
    type: "Multi-day",
    cost: 200,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "The Torrent is based off the design of its sister raft, the Willy Willy. It provides the same interior width space for cargo that a 14 raft does minus room for one box. 13 length shortens the straight section by a foot. Great for paddling and keeps you from colliding with each other. ",
    photoId: "rigs-Maravia-5.png",
  },
  {
    id: 14,
    status: "available",
    name: "NRS Slipstream 120 Fishing Raft Package - fully rigged",
    brand: "NRS",
    type: "Fishing",
    cost: 145,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "The NRS Slipstream 120 Fishing Raft Package features our do-it-all small fishing boat. The Slipstream 120 is built to handle whitewater and flatwater, this compact powerhouse can take a rower and two anglers to the best fishing spots with ease.",
    photoId: "rigs-NRS-3.png",
  },
  {
    id: 15,
    status: "available",
    name: "Pro 16.0 - partially rigged",
    brand: "Hyside",
    type: "Overnight",
    cost: 145,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "Designed to carry 8 loads with ease, the PRO 16.0 delivers and feels like youre driving a 14. Load it down with gear, this boat crushes big water while still staying nimble.",
    photoId: "rigs-Hyside-6.png",
  },
  {
    id: 16,
    status: "available",
    name: "14' DIABLO - partially rigged",
    brand: "Maravia",
    type: "Fishing",
    cost: 95,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "The Diablo has tubes that reduce in size from 20″ on the side to 16″ in the bow and stern to create a lower profile in windy environments, to punch waves easily and for extra room in the bow and stern for gear and people.",
    photoId: "rigs-Maravia-1.png",
  },
  {
    id: 17,
    status: "available",
    name: "10.5 RMR Storm 2-Bay Frame - partially rigged",
    brand: "RMR",
    type: "Fishing",
    cost: 155,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "Introducing RMR's series of lightweight, plug n' play frame packages! The RMR Storm 2-Bay Frame with Low-Back Seat Package comes with EVERYTHING you need to hit the river in style.  Choose your color of the Storm - and leave the rest to us. Our RMR Frame is made in Fayette County, WV by our experienced frame designer and craftsman.  The RMR 2-Bay Frame with Low-Back Seat is made with 1-1/4 Schedule 40 6063 T6 anodized aluminum and Hollaender Speed Rail Fittings and includes a kick bar, custom oar towers, and premium low-back tractor seat.",
    photoId: "rigs-RMR-1.png",
  },
  {
    id: 18,
    status: "available",
    name: "Padillac I Ducky - partially rigged",
    brand: "Hyside",
    type: "Overnight",
    cost: 95,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "Youll find this IK everywhere from flat water floats to class 5 rivers. Designed for performance, built for durability, throw anything at this kayak.",
    photoId: "rigs-Hyside-1.png",
  },
  {
    id: 19,
    status: "available",
    name: "IK-123 The Animas Single Inflatable Kayak",
    brand: "RMR",
    type: "Overnight",
    cost: 75,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "The Animas Inflatable Kayak is durable without sacrificing performance.  Designed with the commercial Outfitter in mind, it comes standard with an I-beam floor, chafers, and baffles.  Seams and are triple-fused with welded seam tape inside and out.  Built with the perfect blend of performance, durability, and stability, our IKs are sure to be a blast regardless of your experience level.",
    photoId: "rigs-RMR-3.png",
  },
  {
    id: 20,
    status: "available",
    name: "13' SCOUT - fully rigged",
    brand: "Maravia",
    type: "Overnight",
    cost: 145,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "The New Maravia Scout is perfect for tight squeezes on multi-day expeditions or install 3 thwarts and it will be your go-to for splashy fun. The diminishing tubes allow for more room in the bow and stern and lower profile in the wind.  The 70” long straight section creates a perfect platform for an oversize box and cooler and 2-3 people when rowing.",
    photoId: "rigs-Maravia-2.png",
  },
  {
    id: 21,
    status: "available",
    name: "NRS E-132D Self-Bailing Raft - fully rigged",
    brand: "NRS",
    type: "Multi-day",
    cost: 220,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "The unique design of the NRS E-132D makes it a blast to run down rivers. Whether paddling, rowing or fishing, you'll love the aggressive personality of our smallest diminishing tube raft.",
    photoId: "rigs-NRS-2.png",
  },
  {
    id: 22,
    status: "available",
    name: "Pro 14.8 - fully rigged",
    brand: "Hyside",
    type: "Overnight",
    cost: 150,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "Its very common to get bookings that add up to 8 plus, but few boat designs will handle them. On Californias American River, where class III and busy weekends are the norm, this 4 thwart people mover was developed. Not much bigger than the other boats on the river but very helpful when extra boats and guides are scarce.",
    photoId: "rigs-Hyside-4.png",
  },
  {
    id: 23,
    status: "available",
    name: "12' RMR Frame Package - fully rigged",
    brand: "RMR",
    type: "Overnight",
    cost: 160,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "Introducing RMR's series of lightweight, plug n' play frame packages with a price you can't beat. The RMR SB120 3-Bay Frame with Poly Deck Package comes with EVERYTHING you need to hit the river in style. Choose your color for the SB120 - and leave the rest to us. RMR Frames are made in Fayette County, WV by our experienced frame designer and craftsman.  The RMR 3-Bay Frame with 1 1/4 Sch 40 6063 T6 Anodized Aluminum with Hollaender Speed Rail Fittings includes a kick bar and custom oar towers.",
    photoId: "rigs-RMR-2.png",
  },
  {
    id: 24,
    status: "available",
    name: "12' RMR Frame Package - partially rigged",
    brand: "RMR",
    type: "Overnight",
    cost: 125,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "Introducing RMR's series of lightweight, plug n' play frame packages with a price you can't beat. The RMR SB120 3-Bay Frame with Poly Deck Package comes with EVERYTHING you need to hit the river in style. Choose your color for the SB120 - and leave the rest to us. RMR Frames are made in Fayette County, WV by our experienced frame designer and craftsman.  The RMR 3-Bay Frame with 1 1/4 Sch 40 6063 T6 Anodized Aluminum with Hollaender Speed Rail Fittings includes a kick bar and custom oar towers.",
    photoId: "rigs-RMR-5.png",
  },
  {
    id: 25,
    status: "available",
    name: "Outfitter 13.0 - fully rigged",
    brand: "Hyside",
    type: "Overnight",
    cost: 145,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "Place it next to our PRO 13.0 and it would be difficult to tell them apart. With all the bells and whistles youd expect, like four main chambers, triple bonded seams and urethane bottom chafers, you cant beat this 6-8 passenger workhorse for the very affordable price. The perfect size for a 3 man fishing rig, with plenty of cargo space, yet narrow enough to sneak into your favorite spots.",
    photoId: "rigs-Hyside-3.png",
  },
  {
    id: 26,
    status: "available",
    name: "Outfitter 14.0 XT - partially rigged",
    brand: "Hyside",
    type: "Multi-day",
    cost: 180,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "Yes, the XT means just that, a little extra in the tubes, the beam and straight tube, for those encounters of just about anything. The perfect gear boat, multi-day, or big water paddle boat. Weve added 5 additional d-rings to the XT, based on your feedback. 1 at each outside quarter panel and 1 at the inside stern. ENJOY!",
    photoId: "rigs-Hyside-5.png",
  },
  {
    id: 27,
    status: "available",
    name: "NRS Otter 140 Self-Bailing Raft",
    brand: "NRS",
    type: "Overnight",
    cost: 165,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "The NRS Otter 140 is the little big man of rafts. At 14' long and 7' wide, it's small enough to navigate tight rivers and large enough to carry heavy loads on multi-day trips. A great fishing boat too!",
    photoId: "rigs-NRS-1.png",
  },
  {
    id: 28,
    status: "available",
    name: "10.5 RMR Storm 2-Bay Frame",
    brand: "RMR",
    type: "Fishing",
    cost: 125,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "Introducing RMR's series of lightweight, plug n' play frame packages! The RMR Storm 2-Bay Frame with Low-Back Seat Package comes with EVERYTHING you need to hit the river in style.  Choose your color of the Storm - and leave the rest to us. Our RMR Frame is made in Fayette County, WV by our experienced frame designer and craftsman.  The RMR 2-Bay Frame with Low-Back Seat is made with 1-1/4 Schedule 40 6063 T6 anodized aluminum and Hollaender Speed Rail Fittings and includes a kick bar, custom oar towers, and premium low-back tractor seat.",
    photoId: "rigs-RMR-4.png",
  },
  {
    id: 29,
    status: "available",
    name: "14' WILLY WILLY - fully rigged",
    brand: "Maravia",
    type: "Fishing",
    cost: 139,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "This ones YOUR baby! The Willy-Willy was created for you and by you. The new design is inspired by one of our most popular rafts, the Williwaw 1. You asked for it, so we filled the gap between the narrower Diablo and the wider Zephyr. The Willy-Willy is perfectly sized to accommodate a 40” drybox and larger cooler.",
    photoId: "rigs-Maravia-4.png",
  },
  {
    id: 30,
    status: "available",
    name: "Cataraft 16.0 - fully rigged",
    brand: "Hyside",
    type: "Multi-day",
    cost: 195,
    rentStartDate: "",
    rentEndDate: "",
    description:
      "This tried-and-true cat hits the sweet spot with gear capacity and maneuverability. Made with the toughest materials you will find on a cat, trust it to get you there and back.",
    photoId: "rigs-Hyside-2.png",
  },
];

export default rigsData;
